// NMK16 MiSTerFPGA project — MC68705R3 peripheral wrapper around jotego's
// jt6805 (jt680x module, vendored via deps.lock's "jtcores" entry into
// rtl/third_party/jt680x/hdl — see tools/bootstrap.sh's seed_jt680x()).
// Used only by tharrierb (Task Force Harrier, Lettering bootleg): its
// "MCU" is a genuine, fully-dumped M68705R3 (mc68705r35.bin, the whole
// 0x1000-byte internal image — bootstrap ROM + option byte + interrupt
// vectors included), not an undumped/simulated protection scheme, so
// this module reproduces the real chip's own register map instead of
// any game-specific behavior (mame/src/devices/cpu/m6805/m68705.{h,cpp}
// is the reference for every register below).
//
// 6805.uc/6805.vh/6805_param.vh alongside this file are jt680x's own
// GENERATED microcode ROM and control-signal headers (jotego's
// `jtframe ucode` build step turns modules/jt680x/ucode/6805.yaml into
// them) — reproduced here with a from-scratch Go re-implementation of
// that generator (jtframe's own module tree pulls in a large dependency
// graph this project has no other use for) rather than regenerated by a
// build step, since the source YAML is fixed. Re-run only if jtcores'
// own 6805.yaml changes upstream.
//
// Address map (M68705R3, 12-bit bus, m6805_hmos_device::internal_map +
// m68705_device + m68705r_device): 0x00/01/02/03 port A/B/C/D data,
// 0x04/05/06 DDR A/B/C (port D has none — it is a dedicated INPUT-only
// port on this chip, matching tharrierb's own driver, which binds
// portd_r but no portd_w), 0x08/09 the timer's TDR/TCR, 0x0A MISC
// (plain r/w latch, `m_mr`), 0x0B PCR (EPROM programming control — only
// bits 1:0 writable, the rest fixed), 0x0E/0x0F ACR/ARR (the analog mux
// select/result — tharrierb's driver binds no analog-input callback at
// all, so these are modelled as inert: ACR echoes 0xF8|mux, ARR reads 0
// always, writes ignored), 0x10-0x7F 112 bytes of RAM, 0x80-0xFFF the
// dumped ROM image (user EPROM, the fixed bootstrap program and the
// interrupt vectors all live in the one committed ROM file, so no
// separate bootstrap-ROM region is needed the way MAME's own driver
// wants one purely to satisfy its own device_rom_region() bookkeeping).
//
// Timer: the M68705R3's constructor leaves it at m6805_timer's own base
// defaults (options=0: neither TIMER_PGM nor TIMER_MOR nor TIMER_NPC),
// meaning TCR's own TIN/TIE bits never reprogram the source/divisor —
// the timer always counts real E-clock cycles (source=CLOCK, divisor
// fixed at 7 — a 128-count prescaler), and TIR/TIM (bits 7/6) still
// gate the interrupt exactly as m6805_timer::update()/tcr_w() implement.
// `cen_e` (pulsing once per real bus cycle, cen/4 — matching jt680x's
// own "crystal = 4x E" convention) drives it once per cycle rather than
// MAME's own once-per-instruction bulk credit; mathematically identical
// for this purely-linear prescale/decrement formula, since summing N
// unit increments through the same modulo-128-then-decrement step gives
// the same running total and the same zero-crossing detections as one
// bulk add of N. A same-cycle CPU write to TDR/TCR (rare — the CPU only
// writes on a `wr` pulse, the free-running update only on cen_e, a
// once-in-128 coincidence) wins over the free-running update that cycle.
module m68705_core #(
	parameter ROM_FILE = "", // sim only ($readmemh, HW_ROMS=0)
	parameter HW_ROMS  = 0
) (
	input        clk,   // clk_sys
	input        cen,   // the chip's own crystal rate (4x E — jt680x's own convention)
	input        reset,

	// ROM load (HW_ROMS=1): a byte-stream write port, one byte per
	// pulse, same shape as nmk_prot_core's rom_we/rom_waddr/rom_wdata.
	input         rom_we,
	input  [11:0] rom_waddr,
	input  [7:0]  rom_wdata,

	input        irq_n,     // external IRQ pin (the 68000's mcu_control_w bit 0, active low)

	output [7:0] porta_out, // output only (tharrierb: porta_w, the mcu_data_r msb)
	output [7:0] portb_out, // output (portb_w, the mcu_data_r lsb) ...
	input  [7:0] portb_in,  // ... and input (portb_r, from the 68000's mcu_data_w)
	output [7:0] portc_out, // output only (portc_w: handshake bits + port D's input select)
	input  [7:0] portd_in,  // input only (portd_r, muxed externally by portc_out[2:0])

	output [11:0] dbg_pc,    // sim/debug only: the address bus (liveness/trace probe)
	output        dbg_valid, // sim/debug only: pulses once per CPU bus write cycle
	output [7:0]  dbg_data,  // sim/debug only: the data being written (dout) alongside dbg_pc
	output [7:0]  dbg_porta  // sim/debug only: the live Port A output latch
);

	// ------------------------------------------------------------------
	// jt6805 core
	// ------------------------------------------------------------------
	wire        wr;
	wire        tstop;
	wire [12:0] addr;
	reg  [7:0]  din;
	wire [7:0]  dout;
	wire        tirq;

	jt6805 u_cpu (
		.rst(reset), .clk(clk), .cen(cen),
		.irq(~irq_n), .tirq(tirq),
		.wr(wr), .tstop(tstop),
		.addr(addr), .din(din), .dout(dout)
	);

	wire [11:0] a = addr[11:0]; // the chip's own address bus is 12 bits (4096-byte map)
	assign dbg_pc = a;
	assign dbg_valid = wr;
	assign dbg_data = dout;
	assign dbg_porta = porta_latch;

	// ------------------------------------------------------------------
	// ROM (0x80-0xFFF) — a plain internal array, written once at reset
	// either from $readmemh (sim) or the rom_we byte stream (hardware).
	// ------------------------------------------------------------------
	// NMK-10: both arrays are read through a register clocked on clk_sys,
	// NOT combinationally. jt6805 samples din on its own `cen` (the chip's
	// 2.4576 MHz crystal, one pulse every ~16 clk_sys), and the address is
	// stable for that whole window, so a clk_sys-registered read settles
	// long before the CPU latches it — while an asynchronous read leaves
	// Quartus unable to infer M10K and builds 4 KB + 112 B out of flops:
	// measured 17,782 ALMs for this module alone, against 41,910 on the
	// device with Gunnail already using 26,492.
	reg [7:0] rom [0:4095];
	reg [7:0] rom_q;
	generate
	if (!HW_ROMS) begin : g_rom_sim
		initial if (ROM_FILE != "") $readmemh(ROM_FILE, rom);
		always @(posedge clk) rom_q <= rom[a];
	end else begin : g_rom_hw
		always @(posedge clk) begin
			if (rom_we) rom[rom_waddr] <= rom_wdata;
			rom_q <= rom[a];
		end
	end
	endgenerate

	// ------------------------------------------------------------------
	// RAM (0x10-0x7F, 112 bytes)
	// ------------------------------------------------------------------
	reg [7:0] ram [0:127];   // 0x10-0x7F used; sized to the full index range so
	                         // the registered read below never leaves the array
	reg [7:0] ram_q;
	wire [6:0] ram_idx = a[6:0] - 7'h10;
	wire       sel_ram = (a >= 12'h010) && (a <= 12'h07F);
	always @(posedge clk) begin
		if (wr & sel_ram) ram[ram_idx] <= dout;   // wr_cpu is declared below; same net
		ram_q <= ram[ram_idx];
	end

	// ------------------------------------------------------------------
	// Address decode (combinational)
	// ------------------------------------------------------------------
	wire sel_porta = (a == 12'h000);
	wire sel_portb = (a == 12'h001);
	wire sel_portc = (a == 12'h002);
	wire sel_portd = (a == 12'h003);
	wire sel_ddra  = (a == 12'h004);
	wire sel_ddrb  = (a == 12'h005);
	wire sel_ddrc  = (a == 12'h006);
	wire sel_tdr   = (a == 12'h008);
	wire sel_tcr   = (a == 12'h009);
	wire sel_misc  = (a == 12'h00A);
	wire sel_pcr   = (a == 12'h00B);
	wire sel_acr   = (a == 12'h00E);
	wire sel_arr   = (a == 12'h00F);
	// 0x0F39-0x0F7F is the gap between the user EPROM (0x0080-0x0F38) and
	// the bootstrap ROM (0x0F80-0x0FF7); m6805_hmos_device::internal_map
	// leaves it out and unmap_value_high() reads it as 0xFF, where the
	// dumped image happens to hold zeros.
	wire sel_rom   = (a >= 12'h080) && !((a >= 12'hF39) && (a <= 12'hF7F));
	wire wr_cpu    = wr; // jt6805's own write strobe, one cen wide

	// ------------------------------------------------------------------
	// Ports A/B/C: 8-bit data latch + DDR each. port_r(n) = latch bit for
	// an output-configured pin (DDR=1), the bound input for an
	// input-configured one (DDR=0) — Port A is open-drain with internal
	// pull-ups on every 68705 variant (m68705u_device's own constructor
	// comment), so its unconnected input bits read 1, not 0; Port B's
	// input side is the 68000's own mcu_data_w byte; Port C has no read
	// callback bound, so m_port_input[2] keeps its 0xFF power-on value and
	// an input-configured Port C bit reads 1 (tharrierb sets DDRC to 0xFF
	// at boot, so this never shows, but port_r's own formula is
	// mask | (latch & ddr) | (input & ~ddr) for every port).
	// ------------------------------------------------------------------
	reg [7:0] porta_latch = 8'h00, porta_ddr = 8'h00;
	reg [7:0] portb_latch = 8'h00, portb_ddr = 8'h00;
	reg [7:0] portc_latch = 8'h00, portc_ddr = 8'h00;
	wire [7:0] porta_rd = (porta_latch & porta_ddr) | (8'hFF & ~porta_ddr);
	wire [7:0] portb_rd = (portb_latch & portb_ddr) | (portb_in & ~portb_ddr);
	wire [7:0] portc_rd = (portc_latch & portc_ddr) | (8'hFF & ~portc_ddr); // no read callback bound: m_port_input[2] stays 0xFF
	assign porta_out = porta_latch;
	assign portb_out = portb_latch;
	assign portc_out = portc_latch;

	// ------------------------------------------------------------------
	// MISC/PCR/ACR/ARR
	// ------------------------------------------------------------------
	reg [7:0] misc_reg = 8'h00;
	reg [7:0] pcr_reg  = 8'hFF;
	reg [2:0] acr_mux  = 3'd0;
	wire [7:0] acr_rd = {5'b11111, acr_mux};

	// ------------------------------------------------------------------
	// Timer (m6805_timer base-class defaults — see the header)
	// ------------------------------------------------------------------
	reg [7:0] tdr = 8'hFF;
	reg [7:0] tcr = 8'h7F;
	localparam TCR_PSC = 8'h08, TCR_TIM = 8'h40, TCR_TIR = 8'h80;
	reg [6:0] prescale = 7'h7F;
	assign tirq = (tcr & TCR_TIR) && !(tcr & TCR_TIM);

	reg [1:0] cen_div = 2'd0;
	wire      cen_e = cen & (cen_div == 2'd3);
	always @(posedge clk) if (cen) cen_div <= cen_div + 2'd1;

	// Free-running prescale/TDR/TIR update (m6805_timer::update(1)), one
	// step every cen_e; the CPU-write block below applies afterward in
	// program order within the same clk_sys cycle, so a same-cycle write
	// to TDR/TCR overrides whatever this step just computed.
	wire [6:0] nx_prescale = prescale + 7'd1;
	wire       nx_wrap     = nx_prescale[6:0] == 7'd0; // wrapped past 127 -> one decrement
	wire [8:0] tdr_eff     = (tdr == 8'h00) ? 9'd256 : {1'b0, tdr};
	wire       nx_interrupt = nx_wrap && (tdr_eff <= 9'd1);

	always @(posedge clk) begin
		if (reset) begin
			porta_latch <= 8'h00; porta_ddr <= 8'h00;
			portb_latch <= 8'h00; portb_ddr <= 8'h00;
			portc_latch <= 8'h00; portc_ddr <= 8'h00;
			misc_reg <= 8'h00; pcr_reg <= 8'hFF; acr_mux <= 3'd0;
			tdr <= 8'hFF; tcr <= 8'h7F; prescale <= 7'h7F;
		end else begin
			if (cen_e) begin
				prescale <= nx_prescale;
				if (nx_wrap) begin
					tdr <= tdr - 8'd1;
					if (nx_interrupt) tcr <= tcr | TCR_TIR;
				end
			end
			if (wr_cpu) begin
				if (sel_porta) porta_latch   <= dout;
				if (sel_portb) portb_latch   <= dout;
				if (sel_portc) portc_latch   <= dout;
				if (sel_ddra)  porta_ddr     <= dout;
				if (sel_ddrb)  portb_ddr     <= dout;
				if (sel_ddrc)  portc_ddr     <= dout;
				if (sel_misc)  misc_reg      <= dout;
				if (sel_pcr)   pcr_reg[1:0]  <= dout[1:0];
				if (sel_acr)   acr_mux       <= dout[2:0];
				if (sel_tdr)   tdr           <= dout;
				if (sel_tcr) begin
					// tcr_w (options=0: neither TIMER_MOR nor TIMER_PGM, so
					// only the PSC-clears-prescaler and TIR-preserve-on-1
					// behaviors apply): new_tir = old_tir & data[7]; every
					// other bit takes the written value directly.
					if (dout[3]) prescale <= 7'd0; // TCR_PSC (write-only, reads as 0 below)
					tcr <= {tcr[7] & dout[7], dout[6:4], 1'b0, dout[2:0]};
				end
			end
		end
	end

	// ------------------------------------------------------------------
	// Read mux (combinational, matching the reference's own per-address
	// read handlers)
	// ------------------------------------------------------------------
	always @(*) begin
		if (sel_rom)         din = rom_q;
		else if (sel_ram)    din = ram_q;
		else if (sel_porta)  din = porta_rd;
		else if (sel_portb)  din = portb_rd;
		else if (sel_portc)  din = portc_rd;
		else if (sel_portd)  din = portd_in;
		else if (sel_ddra)   din = porta_ddr;
		else if (sel_ddrb)   din = portb_ddr;
		else if (sel_ddrc)   din = portc_ddr;
		else if (sel_tdr)    din = tdr;
		else if (sel_tcr)    din = tcr & ~TCR_PSC; // TCR_PSC reads as 0 (write-only)
		else if (sel_misc)   din = misc_reg;
		else if (sel_pcr)    din = pcr_reg;
		else if (sel_acr)    din = acr_rd;
		else if (sel_arr)    din = 8'h00; // no analog input bound on this board
		else                 din = 8'hFF; // unmap_value_high()
	end

endmodule
