# The Template.sdc scaffold this project inherited from Tier 0 left this
# file as just derive_pll_clocks/derive_clock_uncertainty with an empty
# "core specific constraints" placeholder — it never actually sourced
# sys/sys_top.sdc, the MiSTer framework's own real base constraints
# (root 50MHz clock definitions, HPS/SPI/HDMI-I2C virtual clocks, the
# exclusive clock-group partitioning that decouples unrelated PLL/clock
# domains from each other, and a large set of false-path exceptions for
# OSD/config/ascal-parameter signals). Without it, derive_pll_clocks had
# no properly-defined root clocks to derive from and Quartus tried to
# time-relate every clock domain against every other one — including
# genuinely unrelated ones — which is what quartus_sta's own "Design is
# not fully constrained" warnings and several bogus-looking negative
# slack paths actually were.
source sys/sys_top.sdc

derive_pll_clocks
derive_clock_uncertainty

# ------------------------------------------------------------------
# core specific constraints
# ------------------------------------------------------------------
# Every game-logic clock in this core (68000, Z80, video, SDRAM) lives
# on ONE domain, clk_sys, generated by rtl/pll.v's own hand-written
# altpll instance — no interactive Quartus GUI was available in this
# environment to generate the MegaWizard-style altera_pll IP that
# sys/sys_top.sdc's own exclusive-group wildcard
# (*|pll|pll_inst|altera_pll_i|...) expects, so clk_sys's real
# hierarchical clock name doesn't match that pattern and never landed
# in any of sys_top.sdc's mutually-exclusive groups. Confirmed directly
# from a real quartus_sta run: clk_sys's actual node name is
# emu|pll|altpll_component|auto_generated|generic_pll1~PLL_OUTPUT_COUNTER|divclk
# (wildcarded below for the "auto_generated|generic_pll1" middle
# segment, which is Quartus's own internal naming and not guaranteed
# stable across recompiles) — and it was, unsurprisingly, the single
# most common endpoint across every worst-case setup/hold/recovery/
# removal slack line quartus_sta reported. This adds it as its own
# group, exclusive from every other top-level clock domain sys_top.sdc
# already keeps mutually exclusive from each other.
set_clock_groups -exclusive \
	-group [get_clocks {emu|pll|altpll_component|*PLL_OUTPUT_COUNTER|divclk}] \
	-group [get_clocks {pll_hdmi|pll_hdmi_inst|altera_pll_i|*[0].*|divclk}] \
	-group [get_clocks {pll_audio|pll_audio_inst|altera_pll_i|*[0].*|divclk}] \
	-group [get_clocks {spi_sck}] \
	-group [get_clocks {hdmi_sck}] \
	-group [get_clocks {*|h2f_user0_clk}] \
	-group [get_clocks {FPGA_CLK1_50}] \
	-group [get_clocks {FPGA_CLK2_50}] \
	-group [get_clocks {FPGA_CLK3_50}]
