// NMK-110/113/215 TLCS-90 shared-RAM protection MCU board wrapper —
// Tier 2's own Family D (`tdragon_prot_state` in the reference,
// mame/src/mame/nmk/nmk16.cpp:4895-5123 and nmk16.h:281-308). Unlike
// `nmk004_core.sv` (the SOUND-MCU role, exposing YM2203/OKI/host-latch
// ports for a real NMK004 board), this is the PROTECTION-MCU role: a
// second, independent TLCS-90 instance that gets genuine, direct
// read/write access to the 68000's own ENTIRE memory space via a
// literal shared-bus pass-through, plus the ability to HALT the 68000
// outright.
//
// This is the SAME `tlcs90.sv` CPU core every NMK004 board already
// uses (no CPU-core changes needed at all) — only the peripheral role
// differs. Confirmed directly from `mame/src/devices/cpu/tlcs90/
// tlcs90.cpp`: `tmp91640_mem` (this role's own device, "TMP91640"/
// "NMK-110"/"NMK-113") uses the *exact same* `tmp90840_regs` on-chip
// peripheral register map (0xffc0-0xffef) as `tmp90840_mem` (NMK004's
// own device) — only the internal ROM size (16KB here, not 8KB) and
// internal RAM size/location (512 bytes at 0xfdc0-0xffbf, not 256
// bytes at 0xfec0-0xffbf) differ. So `nmk004_periph.sv` is reused
// unchanged (its own header documents the small, additive P5/P6
// override extension this role needs — read-side overrides only,
// tied inert for NMK004's own role).
//
// Memory map (see tdragon_prot_map/tdragon_prot() in nmk16.cpp):
//   0x0000-0x3fff  internal boot ROM (16KB — the actual protection
//                  program; per-game, e.g. nmk-110-tdragon.bin)
//   0xfdc0-0xffbf  internal RAM (512B)
//   0xffc0-0xffef  on-chip peripherals (nmk004_periph.sv, shared module)
//   everything else, in EVERY bank (bank0's own 0x4000-0xfdbf/
//     0xfff0-0xffff, and all of banks 1-15) — direct pass-through to
//     the 68000's own byte-addressed memory space via `bus_addr`/
//     `bus_rd`/`bus_wr`/`bus_wdata`/`bus_rdata`. The reference's own
//     `mcu_side_shared_r/w(offs_t offset)` literally calls
//     `m_maincpu->space(AS_PROGRAM).read_byte(offset)`/`write_byte` —
//     genuine full-bus access, not a narrow shared-RAM window. `offset`
//     there is a 20-bit byte address spanning `0x000000-0x0fffff`,
//     which is exactly what this core's own already-proven IX/IY
//     bank-extension mechanism (`addr_bank` — see tlcs90.sv's header,
//     verified end-to-end by `tb_banktest.cpp`, never previously
//     exercised by any NMK004-role game) produces when concatenated
//     with the 16-bit `addr`: `bus_addr = {addr_bank, addr}`. No new
//     CPU-core work needed — this is the first real (non-synthetic)
//     use of a mechanism the CPU core already implements correctly.
//
// Port 5/6 protection-signalling (confirmed directly against
// `tdragon_prot_state::mcu_port5_r`/`mcu_port6_r`/`mcu_port6_w` in
// nmk16.cpp, not assumed from a generic port-latch model):
//   - **Port 5 read** returns the current scanline position
//     (`screen.vpos()>>2`) — wired here from an external `vpos_div4`
//     input the top-level wrapper drives from the shared `video_timing`
//     instance's own `vcount`.
//   - **Port 6 read** returns a status byte that TOGGLES bit 2 on
//     every read (reset value 0x04) and returns the POST-toggle value
//     (the reference's own C++ toggles `m_bus_status` *then* returns
//     it in the same call — replicated here as a registered toggle
//     whose *read value* is combinationally forwarded to reflect the
//     new state on the very read that caused it, while the register
//     itself settles to that value on the next clock edge).
//   - **Port 6 write** is inspected for two specific values rather
//     than latched as a plain register (the reference's own comment:
//     "the actual mechanism is a little more complex, but these are
//     written at the start and end of the take/release bus function"):
//     `0x08` asserts the 68000's HALT line, `0x0B` releases it; any
//     other value is a no-op (matching the reference's own `else:` log-
//     only branch). Exposed here as a single `halt_68k` output for the
//     top-level wrapper to drive `fx68k`'s own `HALTn` input — every
//     prior port in this project tied `HALTn` permanently high (`1'b1`)
//     since no game before this one could ever actually halt the
//     68000; this is the first real driver for that pin.
//
// Known simplifications: no EXTERNAL interrupt source wiring (the
// reference's own `tdragon_prot()` config wires no interrupt sources
// into `m_protcpu` beyond the port callbacks above — confirmed by
// reading the full config function, not assumed) — `nmi` tied
// inactive. The on-chip TIMER peripheral's own interrupts (already
// generated by the shared `nmk004_periph.sv`'s own `irq_req` output,
// same as NMK004's own role) ARE still wired to the CPU core, since
// those are internal to the TLCS-90 itself and need no external
// config — confirmed necessary in practice: the boot ROM's own main
// loop (`$08B4`: an unconditional `inc (hl)` / `call $08BE` / `jr
// $08B4` background loop) does essentially nothing on its own: the
// actual bus-take/protection-check sequence (`mcu_port6_w(0x08)` at
// `$00B98`) is reached from a periodic timer-interrupt service
// routine, not from that main loop directly — tying irq_req to 0
// leaves the ISR (and therefore the entire protection mechanism)
// unreachable.
// `config.set_maximum_quantum(attotime::from_hz(6000))` in the
// reference (a scheduler-quantum tightening MAME itself needs for this
// specific timing-sensitive interaction) has no RTL analog: this
// design's own single shared `clk_sys` domain already advances every
// module in lockstep every cycle, which is strictly finer-grained than
// any MAME scheduler quantum, so there's no equivalent "coarseness" to
// correct for here.
module nmk_prot_core #(
	parameter BOOT_ROM_FILE = "",
	// Port 7 constant (`port_read<7>().set_constant(...)` in the
	// reference) — some protection ROMs (e.g. NMK-113, shared by
	// hachamf and others) select their own per-game codepath by
	// reading a fixed, hardwired value here; tdragon1's own dedicated
	// NMK-110 ROM wires nothing to port 7 at all, so P7_EXT_EN defaults
	// off (plain read/write latch, inert) for every caller that
	// doesn't need this.
	parameter P7_EXT_EN  = 1'b0,
	parameter [7:0] P7_EXT_VAL = 8'h00
) (
	input clk,
	input reset,

	// 68000 shared-bus master interface — genuine full-map read/write,
	// see header. bus_addr is a 20-bit BYTE address into the 68000's
	// own program space ({addr_bank, addr}).
	output [19:0] bus_addr,
	output        bus_rd,
	output        bus_wr,
	output  [7:0] bus_wdata,
	input   [7:0] bus_rdata,

	// Port 5: current scanline (screen.vpos()>>2) — see header.
	input   [7:0] vpos_div4,

	// Port 6 write 0x08/0x0B: assert/deassert the 68000's own HALT —
	// see header. Active-high (1 = 68000 halted).
	output        halt_68k,

	output [15:0] dbg_pc,
	output        dbg_valid,

	// debug: live HL, for root-causing shared-RAM-content divergences
	// against MAME's own debugger register readout (same technique
	// nmk004_core.sv's own dbg_a/dbg_f/dbg_hl already use). IX/IY
	// aren't exposed by tlcs90.sv itself; bus_addr already shows the
	// effective (ix+n)/(iy+n) address during those accesses.
	output [15:0] dbg_hl
);

	// ------------------------------------------------------------------
	// CPU
	// ------------------------------------------------------------------
	wire [7:0]  cpu_din;
	wire [7:0]  cpu_dout;
	wire [15:0] cpu_addr;
	wire [3:0]  cpu_addr_bank;
	wire        cpu_mem_rd, cpu_mem_wr;
	wire [10:0] irq_mask, irq_req_periph;

	wire [3:0] cpu_bx, cpu_by;

	tlcs90 cpu (
		.clk(clk), .reset(reset),
		.din(cpu_din), .dout(cpu_dout), .addr(cpu_addr), .addr_bank(cpu_addr_bank),
		.mem_rd(cpu_mem_rd), .mem_wr(cpu_mem_wr),
		// irq_req: the on-chip TIMER peripheral's own interrupts, not an
		// external source — see header, this is required for the
		// protection mechanism to ever run at all.
		.nmi(1'b0), .irq_req(irq_req_periph), .irq_mask(irq_mask),
		// ix_bank/iy_bank: fed back from the peripheral's own BX/BY
		// registers (see the periph instantiation below) — this IS the
		// mechanism that reaches the 68000's own extended address space
		// (see header's own {addr_bank,addr} derivation); leaving these
		// unconnected would silently strand every bank-extended access
		// at bank 0 regardless of what firmware writes to BX/BY.
		.ix_bank(cpu_bx), .iy_bank(cpu_by),
		.dbg_pc(dbg_pc), .dbg_valid(dbg_valid), .dbg_halt(),
		.dbg_a(), .dbg_f(), .dbg_hl(dbg_hl)
	);

	// ------------------------------------------------------------------
	// Address decode — see header. Only bank0's own low addresses can
	// ever hit the internal ROM/RAM/peripherals; everything else
	// (including every nonzero bank) is shared-bus pass-through.
	// ------------------------------------------------------------------
	wire bank0        = (cpu_addr_bank == 4'h0);
	wire sel_boot_rom = bank0 && (cpu_addr <= 16'h3fff);
	wire sel_int_ram  = bank0 && (cpu_addr >= 16'hfdc0) && (cpu_addr <= 16'hffbf);
	wire sel_periph   = bank0 && (cpu_addr >= 16'hffc0) && (cpu_addr <= 16'hffef);
	wire sel_shared   = ~(sel_boot_rom | sel_int_ram | sel_periph);

	// ------------------------------------------------------------------
	// Internal ROM/RAM
	// ------------------------------------------------------------------
	reg [7:0] boot_rom [0:16383];
	initial if (BOOT_ROM_FILE != "") $readmemh(BOOT_ROM_FILE, boot_rom);

	reg [7:0] int_ram [0:511];
	wire [8:0] int_ram_addr = cpu_addr - 16'hfdc0;
	always @(posedge clk) if (cpu_mem_wr && sel_int_ram) int_ram[int_ram_addr] <= cpu_dout;

	// ------------------------------------------------------------------
	// Shared-bus master (68000's own memory space) — see header.
	// ------------------------------------------------------------------
	assign bus_addr  = {cpu_addr_bank, cpu_addr};
	assign bus_rd    = sel_shared & cpu_mem_rd;
	assign bus_wr    = sel_shared & cpu_mem_wr;
	assign bus_wdata = cpu_dout;

	// ------------------------------------------------------------------
	// Peripherals — same shared module as nmk004_core.sv's own (see
	// header: TMP91640 uses the identical tmp90840_regs register map).
	// ------------------------------------------------------------------
	wire [7:0] periph_rdata;
	wire       p6_we;
	wire [7:0] p6_wdata;

	// Port 6 read: toggling bus-status byte, "return the new value on
	// the same read that caused the toggle" — see header.
	reg [7:0] bus_status_reg;
	wire      p6_re_now = sel_periph && cpu_mem_rd && (cpu_addr[5:0] == 6'h0c);
	wire [7:0] bus_status_next = bus_status_reg ^ 8'h04;
	wire [7:0] p6_read_value = p6_re_now ? bus_status_next : bus_status_reg;
	always @(posedge clk) begin
		if (reset) bus_status_reg <= 8'h04;
		else if (p6_re_now) bus_status_reg <= bus_status_next;
	end

	// Port 6 write: 0x08/0x0B assert/deassert the 68000's HALT — see header.
	reg halt_r;
	always @(posedge clk) begin
		if (reset) halt_r <= 1'b0;
		else if (p6_we) begin
			if (p6_wdata == 8'h08) halt_r <= 1'b1;
			else if (p6_wdata == 8'h0b) halt_r <= 1'b0;
		end
	end
	assign halt_68k = halt_r;

	nmk004_periph periph (
		.clk(clk), .reset(reset),
		.reg_addr(cpu_addr[5:0]),
		.wdata(cpu_dout),
		.we(sel_periph & cpu_mem_wr),
		.re(sel_periph & cpu_mem_rd),
		.rdata(periph_rdata),
		.irq_mask(irq_mask), .irq_req(irq_req_periph),
		.p4_latch(), .bx(cpu_bx), .by(cpu_by),
		.p5_ext_en(1'b1), .p5_ext_val(vpos_div4),
		.p6_ext_en(1'b1), .p6_ext_val(p6_read_value),
		.p6_we(p6_we), .p6_wdata(p6_wdata),
		.p7_ext_en(P7_EXT_EN), .p7_ext_val(P7_EXT_VAL)
	);

	// ------------------------------------------------------------------
	// Read mux
	// ------------------------------------------------------------------
	reg [7:0] rdata;
	always @(*) begin
		if (sel_boot_rom)     rdata = boot_rom[cpu_addr[13:0]];
		else if (sel_int_ram) rdata = int_ram[int_ram_addr];
		else if (sel_periph)  rdata = periph_rdata;
		else if (sel_shared)  rdata = bus_rdata;
		else                  rdata = 8'h00;
	end
	assign cpu_din = rdata;

endmodule
