#!/usr/bin/env python3
"""Generate the three "NMK16_Raphero" rbf .mra files (arcadian parent, raphero,
rapheroa) from the table below, transcribed from mame/src/mame/nmk/
nmk16.cpp's GAME()/ROM_START/INPUT_PORTS_START(raphero). Part order is
rtl/raphero/raphero_core.sv's fixed SDRAM layout (see the header written
into each file). Run from the repo root:
    python3 tools/gen_raphero_mra.py
"""
import os

# --- nmk_irq V-PROM, streamed as its own <rom index="1"> (2026-09-15) ---
# Each set that uses the real nmk_irq scanline generator carries its own
# 256-byte V-timing PROM. It used to be baked into the bitstream by
# $readmemh, which put arcade PROM content in the shipped .rbf; it now
# arrives over ioctl on its own index, so no SDRAM region base moves.
# Sets absent from this table use the fixed-scanline substitute and need
# no region. ssmissin/airattck/airattcka's dump is half-populated -- the
# core compacts it on load, see gunnail_core.sv's vprom_halfpop.
VPROM = {'vandyke': ('ic100.bpr', '98ed1c97'), 'vandykejal': ('ic100.bpr', '98ed1c97'), 'vandykejal2': ('ic100.bpr', '98ed1c97'), 'tharrier': ('21.bpr', 'fcd5efea'), 'tharrieru': ('21.bpr', 'fcd5efea'), 'tharrierb': ('21.bpr', 'fcd5efea'), 'mustang': ('10.bpr', '633ab1c9'), 'mustangs': ('90058-10', 'de156d99'), 'acrobatm': ('11.ic80', '633ab1c9'), 'macrossbl': ('82s135.bin', '633ab1c9'), 'bioship': ('82s135.ic94', '98ed1c97'), 'sbsgomo': ('82s135.ic94', '98ed1c97'), 'blkheart': ('9.bpr', '98ed1c97'), 'blkheartj': ('9.bpr', '98ed1c97'), 'tdragon': ('91070.10', 'e6ead349'), 'tdragon1': ('91070.10', 'e6ead349'), 'ssmissin': ('ssm-pr1.114', 'ed0bd072'), 'airattck': ('82s147.uh6', 'ed0bd072'), 'airattcka': ('82s147.uh6', 'ed0bd072'), 'hachamf': ('82s135.ic50', '633ab1c9'), 'hachamfa': ('82s135.ic50', '633ab1c9'), 'hachamfb': ('82s135.ic50', '633ab1c9'), 'hachamfp': ('82s135.ic50', '633ab1c9'), 'macross': ('921a09', '633ab1c9'), 'gunnail': ('9_82s135.u72', '633ab1c9'), 'gunnailp': ('9_82s135.u72', '633ab1c9'), 'macross2': ('mcrs2bpr.10', 'e6ead349'), 'macross2k': ('mcrs2bpr.10', 'e6ead349'), 'macross2g': ('mcrs2bpr.10', 'e6ead349'), 'tdragon2': ('10.bpr', 'e6ead349'), 'tdragon3h': ('10.bpr', 'e6ead349'), 'tdragon2a': ('10.bpr', 'e6ead349'), 'bigbang': ('10.bpr', 'e6ead349'), 'bigbanga': ('10.bpr', 'e6ead349'), 'arcadian': ('prom2.u53', 'e6ead349'), 'raphero': ('prom2.u53', 'e6ead349'), 'rapheroa': ('prom2.u53', 'e6ead349'), 'sabotenb': ('8.ic37', '633ab1c9'), 'sabotenba': ('8.ic37', '633ab1c9'), 'bjtwin': ('8.ic37', '633ab1c9'), 'bjtwina': ('8.ic37', '633ab1c9'), 'bjtwinp': ('8.ic37', '633ab1c9'), 'bjtwinpa': ('8.ic37', '633ab1c9'), 'nouryoku': ('8.ic37', '633ab1c9'), 'nouryokup': ('8.ic37', '633ab1c9'), 'powerins': ('21.u71', '182cd81f'), 'powerinsj': ('21.u71', '182cd81f'), 'powerinspu': ('21.u71', '182cd81f'), 'powerinspj': ('21.u71', '182cd81f')}

def vprom_rom_block(setname, zips):
    e = VPROM.get(setname)
    if not e:
        return ""
    fn, crc = e
    return ('\n  <!-- nmk_irq:vtiming -->\n'
            '  <rom index="1" zip="%s" md5="none">\n'
            '    <part crc="%s" name="%s"/>\n'
            '  </rom>\n' % (zips, crc, fn))


RELEASES = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "releases")

HEADER_NOTE = '''<!--
  {desc} — NMK16 "NMK16_Raphero" rbf (arcadian/raphero/rapheroa share the
  raphero() machine config, nmk16.cpp). {origin}

  Transcribed from mame/src/mame/nmk/nmk16.cpp:
    - ROM_START({setname}), GAME(... {setname} ...) line {game_line}
    - INPUT_PORTS_START(raphero): 3 buttons per player, DSW1/DSW2 below

  ROM part order = rtl/raphero/raphero_core.sv's fixed SDRAM layout
  (docs/hw-bringup.md): maincpu @0x000000, audiocpu @0x080000, fgtile
  @0x0A0000, bgtile @0x0C0000, sprites @0x2C0000 (3 files), then the
  OKI sample files ONCE each — rhp94099.5, .6, .7 @0x8C0000: MAME loads
  rhp94099.6 into both oki1 (.6+.7) and oki2 (.5+.6), so the core reads
  oki2 at 0x8C0000 and oki1 at 0xAC0000 from one contiguous copy. The
  ROM_LOAD16_WORD_SWAP regions (maincpu, sprites) need no reordering:
  the core rebuilds words by ioctl byte parity. The nmk_irq timing
  PROMs are fixed at synthesis and not downloaded.
  Generated by tools/gen_raphero_mra.py.
-->
'''

BODY = '''<misterromdescription>
  <name>{desc}</name>
  <mratimestamp>202609090000</mratimestamp>
  <mameversion>0270</mameversion>
  <setname>{setname}</setname>
  <year>1994</year>
  <manufacturer>{manufacturer}</manufacturer>
  <category>Shooter</category>
  <rbf>NMK16_Raphero</rbf>

  <!-- ROT270 in nmk16.cpp -->
  <rotation>1</rotation>

  <!-- DSW1 default 0xF5 (Service Mode off, Language English = bit1
       clear, SW1:6 "Unused" off = bit2 set, SW1:5 "Unused" off = bit3
       clear, Normal, 3 lives), DSW2 default 0xFF. Byte order matches
       raphero_core.sv's decode (sel_dsw1 at 0x100008, sel_dsw2 at
       0x10000A). ids are listed in bit-value order (value 0 first).
       Third byte 0x00 is not a <dip> (no OSD entry over it): bit 6 is
       NMK16_Raphero.sv's hidden "unlock P1/P2 Autofire menu" flag (see its
       autofire_unlock comment) — 00 keeps the menu hidden, same as
       every other game on this rbf. Without this explicit byte the
       core reads the idle 0xFF default and the flag reads set. -->
  <switches default="F5,FF,00">
    <dip bits="0" name="Service Mode" ids="On,Off"/> <!-- PORT_SERVICE_DIPLOC, active low -->
    <dip bits="1" name="Language" ids="English,Japanese"/>
    <dip bits="2" name="Unused (SW1:6)" ids="On,Off"/>
    <dip bits="3" name="Unused (SW1:5)" ids="Off,On"/>
    <dip bits="4,5" name="Difficulty" ids="Hardest,Easy,Hard,Normal"/>
    <dip bits="6,7" name="Lives" ids="1,2,4,3"/>
    <dip bits="8" name="Flip Screen" ids="On,Off"/>
    <dip bits="9" name="Demo Sounds" ids="Off,On"/>
    <dip bits="10,12" name="Coin B" ids="Free_Play,1C_4C,3C_1C,1C_2C,4C_1C,1C_3C,2C_1C,1C_1C"/>
    <dip bits="13,15" name="Coin A" ids="Free_Play,1C_4C,3C_1C,1C_2C,4C_1C,1C_3C,2C_1C,1C_1C"/>
  </switches>

  <buttons names="Button 1,Button 2,Button 3,Start,Coin" default="Y,B,A,Start,R"/>

  <rom index="0" zip="{zip}" md5="none">
    <!-- maincpu, 0x080000 @ 0x000000 (ROM_LOAD16_WORD_SWAP) -->
    <part crc="{main_crc}" name="{main_name}"/>
    <!-- audiocpu (TMP90841), 0x020000 @ 0x080000 -->
    <part crc="fe01ece1" name="rhp94099.2"/>
    <!-- fgtile, 0x020000 @ 0x0A0000 -->
    <part crc="{fg_crc}" name="{fg_name}"/>
    <!-- bgtile, 0x200000 @ 0x0C0000 -->
    <part crc="076eee7b" name="rhp94099.4"/>
    <!-- sprites, 0x600000 @ 0x2C0000 (3 files, ROM_LOAD16_WORD_SWAP) -->
    <part crc="49892f07" name="rhp94099.8"/>
    <part crc="ea2e47f0" name="rhp94099.9"/>
    <part crc="512cb839" name="rhp94099.10"/>
    <!-- OKI samples @ 0x8C0000: oki2 = .5+.6 (0x8C0000), oki1 = .6+.7 (0xAC0000) -->
    <part crc="515eba93" name="rhp94099.5"/>
    <part crc="f1a80e5a" name="rhp94099.6"/>
    <part crc="0d99547e" name="rhp94099.7"/>
  </rom>
{vprom}</misterromdescription>
'''

SETS = [
    dict(setname="arcadian", desc="Arcadia (NMK)", game_line=10746, manufacturer="NMK",
         zip="arcadian.zip", main_crc="8b46d609", main_name="arcadia.3", fg_crc="1c2c4008", fg_name="arcadia.1",
         origin="Parent set."),
    dict(setname="raphero", desc="Rapid Hero (NMK)", game_line=10747, manufacturer="NMK",
         zip="raphero.zip|arcadian.zip", main_crc="3257bfbd", main_name="3", fg_crc="55a7a011", fg_name="rhp94099.1",
         origin="Clone of arcadian; files it shares with the parent are looked up in arcadian.zip."),
    dict(setname="rapheroa", desc="Rapid Hero (Media Trading)", game_line=10748, manufacturer="NMK (Media Trading license)",
         zip="rapheroa.zip|arcadian.zip", main_crc="ec9b4f05", main_name="rhp94099.3", fg_crc="55a7a011", fg_name="rhp94099.1",
         origin="Clone of arcadian; files it shares with the parent are looked up in arcadian.zip."),
]


def main():
    for s in SETS:
        path = os.path.join(RELEASES, s["desc"] + ".mra")
        with open(path, "w") as f:
            f.write(HEADER_NOTE.format(**s) + BODY.format(vprom=vprom_rom_block(s['setname'], s['zip']), **s))
        print("wrote", path)


if __name__ == "__main__":
    main()
