#!/usr/bin/env python3
"""Generate the two "Gunnail" rbf .mra files (gunnail parent, gunnailp)
from the table below, transcribed from mame/src/mame/nmk/nmk16.cpp's
GAME()/ROM_START/INPUT_PORTS_START(gunnail). Run from the repo root:
    python3 tools/gen_gunnail_mra.py
"""
import os

RELEASES = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "releases")

HEADER = '<!--\n  {desc} — NMK16 "Gunnail" rbf (gunnail/gunnailp share the gunnail_prot()\n  machine config, nmk16.cpp). {origin}\n\n  Transcribed from mame/src/mame/nmk/nmk16.cpp:\n    - ROM_START({setname}), GAME(... {setname} ...) line {game_line}\n    - INPUT_PORTS_START(gunnail): 2 buttons per player, DSW1/DSW2 below\n\n  ROM part order = rtl/gunnail/gunnail_core.sv\'s fixed SDRAM layout\n  (docs/hw-bringup.md): maincpu @0x000000, NMK004 program @0x080000,\n  NMK004 boot ROM nmk004.bin @0x090000 (from nmk004.zip — MAME\'s shared\n  NMK004 device ROM), NMK-215 protection ROM @0x092000 (the core copies\n  it into the MCU\'s on-chip ROM during the download), fgtile @0x094000,\n  bgtile @0x0B4000, sprites @0x1B4000, oki1 @0x3B4000, oki2 @0x434000\n  (contiguous — the loader streams the parts back to back).\n  {maincpu_note}\n  The nmk_irq timing PROMs are fixed at synthesis and not downloaded.\n  Generated by tools/gen_gunnail_mra.py.\n-->\n'

BODY = '<misterromdescription>\n  <name>{desc}</name>\n  <mratimestamp>202609090000</mratimestamp>\n  <mameversion>0270</mameversion>\n  <setname>{setname}</setname>\n  <year>{year}</year>\n  <manufacturer>{manufacturer}</manufacturer>\n  <category>Shooter</category>\n  <rbf>Gunnail</rbf>\n\n  <!-- ROT270 in nmk16.cpp -->\n  <rotation>1</rotation>\n\n  <!-- DSW1 default 0xFD (Flip off, Language English = bit1 clear,\n       Normal, four "Unused" off = set), DSW2 default 0xFF. Byte order\n       matches gunnail_core.sv\'s decode (sel_dsw1 at 0x080008, sel_dsw2 at\n       0x08000A). ids are listed in bit-value order (value 0 first). -->\n  <switches default="FD,FF">\n    <dip bits="0" name="Flip Screen" ids="On,Off"/>\n    <dip bits="1" name="Language" ids="English,Japanese"/>\n    <dip bits="2,3" name="Difficulty" ids="Hardest,Hard,Easy,Normal"/>\n    <dip bits="4" name="Unused (SW1:4)" ids="On,Off"/>\n    <dip bits="5" name="Unused (SW1:3)" ids="On,Off"/>\n    <dip bits="6" name="Unused (SW1:2)" ids="On,Off"/>\n    <dip bits="7" name="Unused (SW1:1)" ids="On,Off"/>\n    <dip bits="8" name="Unused (SW2:8)" ids="On,Off"/>\n    <dip bits="9" name="Demo Sounds" ids="Off,On"/>\n    <dip bits="10,12" name="Coin B" ids="Free_Play,1C_4C,3C_1C,1C_2C,4C_1C,1C_3C,2C_1C,1C_1C"/>\n    <dip bits="13,15" name="Coin A" ids="Free_Play,1C_4C,3C_1C,1C_2C,4C_1C,1C_3C,2C_1C,1C_1C"/>\n  </switches>\n\n  <buttons names="Button 1,Button 2,Start,Coin" default="Y,B,Start,R"/>\n\n  <rom index="0" zip="{zip}" md5="none">\n    <!-- maincpu, 0x080000 @ 0x000000 -->\n{maincpu}\n    <!-- NMK004 external program, 0x010000 @ 0x080000 -->\n    <part crc="cd4e55f8" name="92077_2.u101"/>\n    <!-- NMK004 internal boot ROM, 0x002000 @ 0x090000 (nmk004.zip) -->\n    <part crc="8ae61a09" name="nmk004.bin"/>\n    <!-- NMK-215 protection MCU ROM, 0x002000 @ 0x092000 -->\n    <part crc="d355a06f" name="nmk-215.bin"/>\n    <!-- fgtile, 0x020000 @ 0x094000 -->\n    <part crc="{fg_crc}" name="1.u21"/>\n    <!-- bgtile, 0x100000 @ 0x0B4000 (NMK214-scrambled, decoded per fetch) -->\n    <part crc="a9ea2804" name="92077-4.u19"/>\n    <!-- sprites, 0x200000 @ 0x1B4000 (ROM_LOAD16_WORD_SWAP, NMK214-scrambled) -->\n    <part crc="d49169b3" name="92077-7.u134"/>\n    <!-- oki1, 0x080000 @ 0x3B4000 -->\n    <part crc="feb83c73" name="92077-5.u56"/>\n    <!-- oki2, 0x080000 @ 0x434000 -->\n    <part crc="6d133f0d" name="92077-6.u57"/>\n  </rom>\n</misterromdescription>\n'

GUNNAIL_MAIN = '    <!-- ROM_LOAD16_BYTE pair: the low-byte chip (3o.u133, odd MAME\n         offsets) on even stream addresses (map="01"), the high-byte chip\n         (3e.u131) on odd — the core rebuilds 68000 words by byte parity. -->\n    <interleave output="16">\n      <part crc="f114e89c" name="3o.u133" map="01"/>\n      <part crc="61d985b2" name="3e.u131" map="10"/>\n    </interleave>'

GUNNAILP_MAIN = '    <!-- single ROM_LOAD16_WORD_SWAP file, same byte order as the pair -->\n    <part crc="93570f03" name="3.u132"/>'

SETS = [{'setname': 'gunnail', 'desc': 'GunNail (28th May. 1992)', 'game_line': 10732, 'year': 1993, 'manufacturer': 'NMK / Tecmo', 'zip': 'gunnail.zip|nmk004.zip', 'maincpu': '    <!-- ROM_LOAD16_BYTE pair: the low-byte chip (3o.u133, odd MAME\n         offsets) on even stream addresses (map="01"), the high-byte chip\n         (3e.u131) on odd — the core rebuilds 68000 words by byte parity. -->\n    <interleave output="16">\n      <part crc="f114e89c" name="3o.u133" map="01"/>\n      <part crc="61d985b2" name="3e.u131" map="10"/>\n    </interleave>', 'fg_crc': '3d00a9f4', 'origin': 'Parent set.', 'maincpu_note': 'maincpu is a ROM_LOAD16_BYTE pair, interleaved below.'}, {'setname': 'gunnailp', 'desc': 'GunNail (location test)', 'game_line': 10733, 'year': 1992, 'manufacturer': 'NMK', 'zip': 'gunnailp.zip|gunnail.zip|nmk004.zip', 'maincpu': '    <!-- single ROM_LOAD16_WORD_SWAP file, same byte order as the pair -->\n    <part crc="93570f03" name="3.u132"/>', 'fg_crc': 'bdf427e4', 'origin': 'Clone of gunnail; files it shares with the parent are looked up in gunnail.zip.', 'maincpu_note': 'maincpu is a single ROM_LOAD16_WORD_SWAP file.'}]


def main():
    for s in SETS:
        path = os.path.join(RELEASES, s["desc"] + ".mra")
        with open(path, "w") as f:
            f.write(HEADER.format(**s) + BODY.format(**s))
        print("wrote", path)


if __name__ == "__main__":
    main()
